# Generated by Django 4.0.6 on 2022-07-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='miniourl',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
