# Generated by Django 4.1 on 2022-08-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('postedAt', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
