# Generated by Django 4.0.6 on 2022-08-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('username', models.CharField(max_length=255, null=True)),
                ('postedAt', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='api/images')),
                ('miniourl', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
